# Host tools, applications and fonts owned by Homebrew.
# Only package-level trust is allowed.

brew "wget"
brew "cloc"
brew "telnet"
brew "graphviz"
brew "lrzsz"
brew "neovim"
brew "fzf"
brew "thefuck"
brew "tig"
brew "httpie"
brew "autojump"
brew "tmux"
brew "ripgrep"
brew "diff-so-fancy"
brew "lazygit"
brew "tree"
brew "scrcpy"
brew "coreutils"
brew "daipeihust/tap/im-select", trusted: true
brew "gron"
brew "stow"
brew "mise"
brew "herdr"
brew "gh"
brew "glab"
brew "fastfetch"
brew "fish"
brew "zoxide"
brew "fd"
brew "bat"
brew "leaf-markdown-viewer"
brew "witr"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "starship"

cask "sublime-text"
cask "visual-studio-code"
cask "surge"
cask "wechat"
cask "feishu"
cask "intellij-idea"
cask "pycharm"
cask "kap"
cask "appcleaner"
cask "keycastr"
cask "the-unarchiver"
cask "vlc"
cask "omnidisksweeper"
cask "qqmusic"
cask "android-platform-tools"
cask "bruno"
cask "zspace"
cask "shottr"
cask "raycast"
cask "google-chrome"
cask "microsoft-excel"
cask "microsoft-word"
cask "microsoft-powerpoint"
cask "microsoft-outlook"
cask "zed"
cask "font-hack-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "chatgpt"
cask "obsidian"
cask "1password"
cask "1password-cli"
cask "antigravity"
cask "ghostty"
cask "hammerspoon"
cask "detachhead/tap/rebased", trusted: true
cask "muxy-app/tap/muxy", trusted: true
# Skip Thaw on macOS 27 and later.
case MacOS.version.major.to_i
when 26
  cask "thaw"
when 14..25
  # The local tap reads committed Cask definitions from this repository.
  tap "danshan/env", File.expand_path(__dir__)
  cask "danshan/env/thaw@1", trusted: true
end
cask "localsend/localsend/localsend", trusted: true
