# https://herdr.dev/docs/configuration/#agent-session-restore

onboarding = false

[theme]
name = "catppuccin"

[ui]
agent_panel_scope = "all"
show_agent_labels_on_pane_borders = false

[worktrees]
directory = "~/.Documents/worktrees"

[experimental]
pane_history = true

[session]
resume_agents_on_restore = true

[keys]
split_vertical = "prefix+ctrl+v"
split_horizontal = "prefix+ctrl+h"

[[keys.command]]
key = "prefix+ctrl+g"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "prefix+ctrl+y"
type = "pane"
command = "yazi"


